name: Emerson Goo
url: https://emersongoo.github.io/
description: a closely watched pot

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
