# main text of home
name: Emerson Goo
bio: Someone, somewhere.

# twitter summary info
description: Emerson Goo - Landing Page

picture: assets/images/picture.jpg

url: http://emersongoo.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# github: mygithub
email: egoo.1234levelup@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
